import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Icon, Notice, PasswordInput } from '../components/ui'

export function Login() {
  const [error, setError] = useState(false)
  const { register, handleSubmit } = useForm<{ username: string; password: string }>()
  return <main className="login-page"><div className="login-card"><aside className="login-aside"><div><div className="brand"><span className="brand-icon"><Icon name="calendar" /></span><span>SISAGEN<small>OPERAÇÃO & FILA</small></span></div><div className="eyebrow">AMBIENTE OPERACIONAL</div><h2>Gestão Concorrente & Governança de Pauta</h2><p>Plataforma centralizada para validação de registros, eliminação de duplicidades e acompanhamento de agendamentos institucionais.</p></div><div className="login-context"><Icon name="shield" /><h3>Uma fila. Informações centralizadas.</h3><p>Consulte solicitações e acompanhe o andamento dos registros em um só lugar.</p></div><small>Acesso individual ao sistema de agendamento</small></aside><section className="login-form"><span className="badge info"><Icon name="shield" /> Autenticação Restrita SCR-001</span><h1>Acesso ao Sistema</h1><p>Entre com suas credenciais individuais para gerenciar a fila de agendamentos.</p><Notice>O acesso às contas está aguardando habilitação. Entre em contato com o administrador.</Notice>{error && <Notice error>Não foi possível autenticar: o serviço de acesso ainda não está disponível.</Notice>}<form onSubmit={handleSubmit(() => setError(true))}><label htmlFor="username">Usuário ou Matrícula Operacional</label><input id="username" autoComplete="username" placeholder="Ex: OP-48920 ou nome.usuario" required {...register('username', { required: true })} /><label htmlFor="password">Chave de Acesso Individual</label><PasswordInput id="password" autoComplete="current-password" placeholder="Digite sua chave de acesso" required {...register('password', { required: true })} /><button className="primary login-submit" type="submit">Entrar no Sistema <Icon name="arrow" /></button></form><footer>Sistema de Agendamento v1.0<small>Acesso Restrito a Usuários Autorizados</small></footer></section></div></main>
}
