import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Modal, Notice, PageHeader, PasswordInput, Stats, Unavailable } from '../components/ui'

interface UserFields { nome: string; email: string; password: string; perfil: string; ativo: boolean }
export function Users() {
  const [open, setOpen] = useState(false)
  const [message, setMessage] = useState(false)
  const [search, setSearch] = useState('')
  const [profile, setProfile] = useState('')
  const [status, setStatus] = useState('')
  const { register, handleSubmit, reset } = useForm<UserFields>({ defaultValues: { perfil: 'AGENDADOR', ativo: true } })
  const close = () => { setOpen(false); setMessage(false); reset() }
  return <><PageHeader eyebrow="Módulo Administrativo / Controle de Acessos" title="Administração de Usuários" description="Gerencie contas de acesso, perfis operacionais e controle de ativação."><button disabled title="Relatório de logins ainda indisponível">Relatório de Logins</button><button className="primary" onClick={() => setOpen(true)}>+ Novo Usuário</button></PageHeader><Stats items={[{ label: 'Total de Usuários', value: '—', hint: 'contas registradas' }, { label: 'Contas Ativas', value: '—', hint: 'contas habilitadas', tone: 'green' }, { label: 'Contas Inativas', value: '—', hint: 'bloqueadas ou suspensas' }]} /><Unavailable>A administração de contas está aguardando habilitação. Nenhum usuário pode ser consultado ou alterado nesta tela por enquanto.</Unavailable><section className="card"><div className="filters"><input type="search" aria-label="Pesquisar usuários" placeholder="Buscar por nome ou e-mail…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Perfil de acesso" value={profile} onChange={e => setProfile(e.target.value)}><option value="">Todos os Perfis</option><option>Administrador</option><option>Cadastrador</option><option>Agendador</option></select><select aria-label="Status da conta" value={status} onChange={e => setStatus(e.target.value)}><option value="">Status: Todos</option><option>Ativos</option><option>Desativados</option></select><button onClick={() => { setSearch(''); setProfile(''); setStatus('') }}>Limpar</button></div><div className="table-scroll" role="region" aria-label="Tabela de usuários" tabIndex={0}><table><thead><tr>{['Identificação / Nome Completo', 'Login / E-mail', 'Perfil de Acesso', 'Status', 'Último Acesso', 'Ações'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody><tr><td colSpan={6} className="empty">Consulta de usuários indisponível.</td></tr></tbody></table></div><div className="pagination"><span>Nenhum dado carregado</span><div className="actions"><button disabled>Anterior</button><span>1</span><button disabled>Próxima</button></div></div></section>
  {open && <Modal title="Novo Usuário" onClose={close}><p>Preencha as credenciais e defina o perfil de acesso.</p><Unavailable>O cadastro de usuários ainda não está disponível. Os dados deste formulário não serão enviados.</Unavailable>{message && <Notice error>Não foi possível salvar: aguarde a habilitação da administração de contas.</Notice>}<form onSubmit={handleSubmit(() => setMessage(true))}><label htmlFor="user-name">Nome Completo *</label><input id="user-name" autoComplete="name" required {...register('nome', { required: true })} /><label htmlFor="user-email">E-mail institucional *</label><input id="user-email" type="email" autoComplete="username" required {...register('email', { required: true })} /><label htmlFor="user-password">Senha Temporária de Acesso *</label><PasswordInput id="user-password" minLength={8} autoComplete="new-password" required {...register('password', { required: true, minLength: 8 })} /><small>Mínimo de 8 caracteres</small><fieldset><legend>Perfil de Acesso & Permissões *</legend>{[{ id: 'AGENDADOR', title: 'Agendador', detail: 'Criação e consulta de solicitações.' }, { id: 'CADASTRADOR', title: 'Cadastrador', detail: 'Conferência e conclusão dos cadastros.' }, { id: 'ADMINISTRADOR', title: 'Administrador', detail: 'Gestão de usuários e operações administrativas.' }].map(role => <label className="role-option" key={role.id}><input type="radio" value={role.id} {...register('perfil')} /><span><strong>{role.title}</strong><small>{role.detail}</small></span></label>)}</fieldset><label className="checkbox"><input type="checkbox" {...register('ativo')} /> Conta Habilitada para Login</label><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button type="submit" className="primary">Salvar Usuário</button></div></form></Modal>}</>
}
